# Standards: 0.11
---

# 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)

- name: 4.1.1.3- Check if CIS audit.d configuration file exists
  stat:
    path: "{{ cis_audit_auditd_filename }}"
  register: auditd_4_1_1_3
  tags:
    - level-1
    - section-1
    - "4.1.1.3"
    - scored

- name: Create the file, if it doesnt exist already
  file:
    path: "{{ cis_audit_auditd_filename }}"
    state: touch
  when: auditd_4_1_1_3.stat.exists == False
  tags:
    - level-2
    - section-4
    - "4.1.1.3"
    - scored

- name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
  lineinfile:
    regexp: "^max_log_file_action"
    line: "max_log_file_action = keep_logs"
    dest: "{{ cis_audit_auditd_filename }}"
    state: present
  notify: Restart auditd
  when: auditd_4_1_1_3.stat.exists == True
  tags:
    - level-2
    - section-4
    - "4.1.1.3"
    - scored


